### ISSUE TITLE
17. Deployement to Either Vercel or Railway

### ISSUE THREAD

**Issue by OkomoJacob** [OkomoJacob/lims-admin#24]
- You can finish taking a look at the Deployment issue with the Vercel that we tried today.

**Comment by henriod** [comment]
Fixed by [cc85083](https://github.com/OkomoJacob/lims-admin/commit/cc85083e2d5edffe24f8be022a355c8726fa8bc4)

**Comment by henriod** [comment]
Working with vercel deployment
